spring.application.name=smartlab-monitor

server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:smartlabdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Swagger (http://localhost:8080/swagger-ui.html)
springdoc.swagger-ui.path=/swagger-ui.html

# Mensagens de erro detalhadas
server.error.include-message=always

# Garante que o data.sql rode depois que o Hibernate criar as tabelas
spring.jpa.defer-datasource-initialization=true
